/* ── VERITAS Civic Dictionary ── */
window.VERITAS_GLOSSARY = {

  /* ── General Political & Legal Terms ── */
  "cadre deployment": "The practice of appointing party loyalists to government, SOE, and institutional positions based on political allegiance rather than professional merit.  The Zondo Commission found it was a key enabler of State Capture.",
  "Zondo Commission": "The Judicial Commission of Inquiry into Allegations of State Capture, Corruption and Fraud in the Public Sector (2018–2022).  It exposed massive corruption under former President Jacob Zuma and produced a 5,000‑page report.",
  "State Capture": "The systemic corruption of state institutions by private interests and political actors, as documented by the Zondo Commission.  An estimated R500 billion was stolen.",
  "Chapter 9 institutions": "Independent bodies established under Chapter 9 of the Constitution to safeguard democracy.  They include the Public Protector, the South African Human Rights Commission (SAHRC), and the Electoral Commission (IEC).",
  "Public Protector": "A Chapter 9 institution that investigates complaints against government and public officials.  Its recommendations are not legally binding unless confirmed by a court.",
  "NHI": "National Health Insurance — a proposed single‑payer healthcare system that would centralise all health funding under the state, aiming for universal coverage.  Highly controversial due to its cost and the potential elimination of private healthcare.",
  "BEE": "Black Economic Empowerment — a set of policies designed to redress economic inequalities by promoting black ownership, management, and employment.  Often criticised for benefiting a politically connected elite rather than the poor.",
  "SOE": "State‑Owned Enterprise — companies like Eskom, Transnet, and SAA that are owned by the government.  Many have been plagued by mismanagement, debt, and corruption.",
  "Ingonyama Trust": "A statutory body established in 1994 that holds about 2.8 million hectares of traditional land in KwaZulu‑Natal on behalf of the Zulu monarch.  Critics say it perpetuates feudal control; defenders say it protects communal land.",
  "Section 25": "The property clause of the South African Constitution, which protects property rights but allows for expropriation with just and equitable compensation.  A focal point of land reform debates.",
  "TRC": "Truth and Reconciliation Commission — the post‑apartheid body that investigated human rights abuses committed between 1960 and 1994.  It granted amnesty in exchange for full disclosure, but was criticised for prioritising truth over justice.",
  "Marikana massacre": "The killing of 34 striking mineworkers by police in 2012 at Lonmin’s Marikana platinum mine.  A watershed moment in post‑apartheid labour relations and state violence.",
  "BRICS": "An economic bloc of Brazil, Russia, India, China, and South Africa.  SA joined in 2010 to strengthen South‑South cooperation and reduce reliance on Western‑dominated institutions.",
  "ICC": "International Criminal Court — a global court that prosecutes war crimes, genocide, and crimes against humanity.  South Africa attempted to withdraw in 2016, citing bias against African leaders.",
  "GNU": "Government of National Unity — a coalition government formed after the 2024 elections, including the ANC, DA, IFP, and several smaller parties.  It echoes the transitional government of the early 1990s.",
  "PAC": "Pan Africanist Congress of Azania — a liberation movement that split from the ANC in 1959, advocating for African nationalism and the return of land to indigenous people.",
  "ubuntu": "A Nguni philosophy meaning 'humanity to others' or 'I am because we are'.  It underpins South Africa’s constitutional values of community, reconciliation, and collective responsibility.",
  "closed shop agreement": "A labour agreement that requires all workers in a specific workplace to join a particular union.  It strengthens collective bargaining but can infringe on individual worker choice.",
  "Scorpions": "The Directorate of Special Operations — a now‑defunct elite crime‑fighting unit that was highly effective but was disbanded in 2009, allegedly for political reasons.",
  "CITES": "Convention on International Trade in Endangered Species — an international agreement that regulates trade in threatened wildlife, including rhino horn and ivory.",
  "fracking": "Hydraulic fracturing, a technique to extract shale gas by injecting high‑pressure fluid underground.  Proposed for the Karoo, but controversial due to water pollution risks in a drought‑prone region.",
  "NSFAS": "National Student Financial Aid Scheme — a government programme providing loans and bursaries to disadvantaged students.  The 'missing middle' refers to students who earn too much to qualify for NSFAS but cannot afford fees.",
  "GBV": "Gender‑Based Violence — widespread physical, sexual, and psychological violence predominantly targeting women and girls.  South Africa has one of the highest rates globally.",
  "CGE": "Commission for Gender Equality — a Chapter 9 institution that promotes gender equality and investigates complaints of gender discrimination.",
  "SADC": "Southern African Development Community — a regional economic bloc of 16 southern African countries aimed at socio‑economic integration and political cooperation.",
  "Eskom": "South Africa’s state‑owned electricity utility.  Struggling with debt, ageing infrastructure, and rolling blackouts (load shedding).",
  "Transnet": "The state‑owned freight transport and logistics company, operating ports, railways, and pipelines.  Faces similar challenges to Eskom with allegations of corruption and inefficiency.",
  "load shedding": "Planned, rolling electricity blackouts implemented by Eskom to prevent a total grid collapse.  A daily reality that has crippled the economy and fuelled public anger.",
  "Section 19": "The constitutional right to vote and stand for public office.  VERITAS is explicitly built in the spirit of this right — advisory, not directive.",
  "CBDC": "Central Bank Digital Currency — a digital form of fiat currency issued by a central bank.  The SARB is exploring a digital rand.",
  "ECD": "Early Childhood Development — programmes and services for children from birth to age 5, critical for school readiness.",
  "SMMEs": "Small, Medium, and Micro Enterprises — small businesses that are key to job creation and economic growth.",
  "BITs": "Bilateral Investment Treaties — agreements between two countries to protect and promote foreign investment.  SA has cancelled several over concerns they limit policy space.",
  "FDI": "Foreign Direct Investment — investment made by a company or individual in one country into business interests in another country.",
  "SAPS": "South African Police Service — the national police force.",
  "NPA": "National Prosecuting Authority — the agency responsible for prosecuting criminal cases.  Its independence has been questioned, especially after State Capture.",
  "UIF": "Unemployment Insurance Fund — provides short‑term relief to workers when they become unemployed or are unable to work.",
  "MRC": "Medical Research Council — a government‑funded organisation that conducts and supports health research.",
  "LGBTQ+": "Lesbian, Gay, Bisexual, Transgender, Queer/Questioning, and other sexual and gender minorities.",
  "JSE": "Johannesburg Stock Exchange — the largest stock exchange in Africa.",
  "IMF": "International Monetary Fund — an international organisation that provides financial assistance and advice to member countries, often with strict conditions.",
  "AU": "African Union — a continental union of 55 African countries, aiming for greater unity and cooperation.",
  "ICJ": "International Court of Justice — the principal judicial organ of the United Nations, which settles disputes between states.",
  "NYDA": "National Youth Development Agency — a state agency aimed at addressing youth development issues, though it has been criticised for wasteful expenditure.",
  "SABC": "South African Broadcasting Corporation — the public broadcaster, funded by advertising and government bailouts.",
  "RDP": "Reconstruction and Development Programme — a post‑apartheid government programme to provide housing and basic services.",
  "CODESA": "Convention for a Democratic South Africa — the negotiations in the early 1990s that led to the end of apartheid and the drafting of the interim Constitution.",
  "COPE": "Congress of the People — a political party formed in 2008 by former ANC members opposed to Jacob Zuma.",
  "constitutional democracy": "A system of government in which the powers of the majority are exercised within a framework of constitutional restraints designed to guarantee all citizens certain fundamental rights.",
  "separation of powers": "The division of government responsibilities into distinct branches — executive, legislative, and judicial — to prevent any one branch from exercising the core functions of another.",
  "judicial review": "The power of courts to examine the actions of the legislative and executive branches and to declare those actions unconstitutional if they violate the Constitution.",
  "proportional representation": "An electoral system in which parties gain seats in proportion to the number of votes cast for them.  South Africa uses a pure PR system.",
  "mixed electoral system": "An electoral system that combines elements of proportional representation and constituency‑based voting.",
  "recall mechanism": "A procedure that allows voters to remove an elected official from office before their term has ended.",
  "subpoena": "A legal document ordering a person to attend court or produce evidence.",
  "secret ballot": "A voting method in which a voter’s choices are anonymous, protecting them from intimidation or retribution.",
  "floor crossing": "The practice of an elected member changing their party affiliation during a term of office.",
  "affirmative action": "Policies designed to address historical discrimination by providing opportunities to members of disadvantaged groups.",
  "sunset clause": "A provision that automatically terminates a law or programme after a specified date unless it is formally renewed.",
  "colonialism": "The policy or practice of acquiring full or partial political control over another country, occupying it with settlers, and exploiting it economically.",
  "apartheid": "The former policy of racial segregation and discrimination enforced by the National Party government from 1948 to 1994.",
  "Bantustan": "A territory set aside for black inhabitants of South Africa and South West Africa (now Namibia) as part of the policy of apartheid.",
  "Pan‑Africanism": "A worldwide movement that aims to encourage and strengthen bonds of solidarity between all indigenous and diasporas of African ancestry.",
  "Marxism‑Leninism": "A communist ideology that combines the theories of Karl Marx and Vladimir Lenin, advocating for a revolutionary vanguard party to lead the working class.",
  "social democracy": "A political ideology that supports economic and social interventions to promote social justice within a capitalist framework, typically through a welfare state.",
  "classical liberalism": "A political ideology that values individual freedom, limited government, free markets, and the rule of law.",
  "neo‑liberalism": "A modern revival of classical liberalism that emphasises free‑market capitalism, deregulation, and a reduced role for the state.",
  "federalism": "A system of government in which power is divided between a central authority and constituent political units (like provinces or states).",
  "secularism": "The principle of separating government institutions and persons mandated to represent the state from religious institutions and religious dignitaries.",
  "traditional authority": "The authority of traditional leaders (such as chiefs and kings) recognised by the Constitution, particularly in rural areas.",
  "restorative justice": "An approach to justice that focuses on repairing the harm caused by criminal behaviour through cooperation between victims, offenders, and the community.",
  "plea bargain": "An agreement in a criminal case between the prosecutor and defendant in which the defendant agrees to plead guilty in exchange for a concession from the prosecutor.",
  "carbon tax": "A tax levied on the burning of carbon‑based fuels, intended to reduce greenhouse gas emissions.",
  "fiscal conservatism": "A political and economic philosophy regarding fiscal policy and fiscal responsibility advocating low taxes, reduced government spending, and minimal government debt.",
  "UBI": "Universal Basic Income — a periodic cash payment unconditionally delivered to all individuals on an individual basis, without means test or work requirement.",

  /* ── South African Political Parties ── */
  "ANC": "African National Congress — the governing party of South Africa since 1994.  Originally a liberation movement, its platform blends African nationalism, social democracy, and developmental state philosophy.",
  "DA": "Democratic Alliance — the largest opposition party.  Rooted in liberal democracy, constitutional governance, and market‑led economic policy.  Governs the Western Cape.",
  "EFF": "Economic Freedom Fighters — a radical left‑wing party founded by Julius Malema in 2013.  Advocates nationalisation, land expropriation without compensation, and Pan‑Africanism.",
  "MK": "uMkhonto weSizwe Party — a breakaway party formed in 2023 with a strong Zulu nationalist base, largely built around Jacob Zuma’s personal appeal.",
  "MKP": "uMkhonto weSizwe Party — see MK.  The acronym MKP is often used interchangeably.",
  "IFP": "Inkatha Freedom Party — a conservative party with Zulu traditionalist roots, founded by Mangosuthu Buthelezi in 1975.  A pragmatic coalition partner with deep regional strength in KwaZulu‑Natal.",
  "PA": "Patriotic Alliance — a populist party strong in coloured communities, founded by Gayton McKenzie.  Skilled at capturing swing wards in coalitions.",
  "ActionSA": "A reform party founded by Herman Mashaba in 2021, focusing on urban governance, anti‑corruption, and strict immigration enforcement.",
  "FF+": "Freedom Front Plus — a conservative Afrikaner‑interest party founded in 1994.  Strong on minority rights, federalism, and cultural preservation.",
  "RISE": "RISE Mzansi — a technocratic reform party founded in 2022 by former editor Songezo Zibi.  Targets educated urban professionals.",
  "BOSA": "Build One South Africa — a community‑first independent movement founded in 2023 by former DA leader Mmusi Maimane.",
  "UDM": "United Democratic Movement — a centrist party founded by Bantu Holomisa in 1997, with a strong anti‑corruption focus.",
  "Al Jama-ah": "A Muslim‑interest party founded in 2007, representing Muslim community interests, particularly in the Western Cape.",
  "ACDP": "African Christian Democratic Party — a Christian conservative party founded in 1993, with a consistent voting base on moral and family issues.",
  "ATM": "African Transformation Movement — a conservative Africanist party founded in 2018, focusing on traditional values and African spirituality.",
  "GOOD": "Good Party — a social democratic party founded by Patricia de Lille in 2018, focusing on spatial justice and urban transformation.",
  "PAC": "Pan Africanist Congress of Azania — a historic liberation movement founded in 1959, advocating Africanism and the return of land.",
  "NCC": "National Coloured Congress — a regional party representing coloured community interests, primarily in the Western Cape.",
  "NFP": "National Freedom Party — an IFP breakaway formed in 2011, focusing on rural KZN development and women empowerment.",
  "UAT": "United Africans Transformation — a radical pan‑Africanist breakaway, focused on black economic empowerment.",
  "SACP": "South African Communist Party — a Marxist‑Leninist party in alliance with the ANC, founded in 1921.  The oldest communist party in Africa.",
  "F4SD": "Forum for Service Delivery — a grassroots movement focused on basic service delivery in townships and rural areas.",
  "ABC": "Abantu Batho Congress — a community‑based party focusing on traditional values and local economic development.",
  "MAP16": "MAP16 Civic Movement — a local civic organisation focused on municipal accountability and ratepayer rights.",
  "AIC": "African Independent Congress — a regional party formed around a municipal boundary dispute in Matatiele.",
  "COPE": "Congress of the People — an ANC breakaway formed in 2008, once the official opposition, now a minor player.",
  "ICOSA": "Independent Civic Organisation of SA — a civic organisation focused on independent local governance.",
  "APC": "African People’s Convention — a PAC breakaway, maintaining an Africanist focus.",
  "UIM": "United Independent Movement — a centrist independent movement strong on individual freedoms and small government.",
  "PBI": "Plaaslike Besorgde Inwoners — an Afrikaans community‑focused party.",
  "CAPEXIT": "Cape Independence Party — a single‑issue party advocating for Western Cape independence.",
  "AZAPO": "Azanian People’s Organisation — born from the Black Consciousness Movement of Steve Biko.",
  "DLC": "Democratic Liberal Congress — a small liberal party.",
  "MF": "Minority Front — represents Indian South African interests, primarily in KZN.",
  "IRC": "International Revelation Congress — a religiously‑aligned party.",
  "BPSA": "Bolsheviks Party of South Africa — a revolutionary socialist party.",
  "TSSA": "Team Sugar South Africa — a single‑issue party focused on the sugar industry.",
  "ADeC": "African Democratic Change — a small reformist party.",
  "BRA": "Better Residents Association — a local residents’ association turned political party.",
  "PAU": "Power of Africans Unity — a pan‑Africanist party.",
  "AASD": "Afrikan Alliance of Social Democrats — a social democratic party with an Afrikaner base.",

  /* ── Key People ── */
  "Cyril Ramaphosa": "Current President of South Africa and leader of the ANC.  A trade unionist, CODESA negotiator, and businessman.  His presidency has been marked by efforts to combat corruption but criticised for slow progress.",
  "John Steenhuisen": "Leader of the Democratic Alliance since 2019.  Former KZN farmer and long‑time DA organiser.",
  "Julius Malema": "Leader of the Economic Freedom Fighters.  A brilliant but polarising political communicator, convicted of fraud.  His lifestyle contradicts his revolutionary rhetoric.",
  "Jacob Zuma": "Former President of South Africa (2009–2018).  His tenure was marred by massive corruption scandals, and the Zondo Commission found he was the central figure in State Capture.  Convicted of contempt of court.",
  "Mangosuthu Buthelezi": "Founder of the Inkatha Freedom Party and a towering but controversial figure in Zulu politics.  He died in 2023 at the age of 95.",
  "Velenkosini Hlabisa": "Current leader of the IFP, succeeding Buthelezi.",
  "Gayton McKenzie": "Leader of the Patriotic Alliance.  A former armed robber turned motivational speaker and politician.",
  "Herman Mashaba": "Founder of ActionSA and former DA mayor of Johannesburg.  A self‑made businessman and anti‑immigration advocate.",
  "Pieter Groenewald": "Leader of the Freedom Front Plus.",
  "Songezo Zibi": "Leader of RISE Mzansi.  Former editor of Business Day.",
  "Mmusi Maimane": "Leader of Build One South Africa.  Former leader of the DA and the first black leader of a major SA opposition party.",
  "Bantu Holomisa": "Leader of the United Democratic Movement.  A former Transkei military ruler turned democracy advocate, highly credible on anti‑corruption.",
  "Ganief Hendricks": "Leader of Al Jama-ah.",
  "Kenneth Meshoe": "Leader of the African Christian Democratic Party.  A pastor and long‑serving MP.",
  "Vuyolwethu Zungula": "Leader of the African Transformation Movement.",
  "Patricia de Lille": "Leader of the Good Party and current Minister of Public Works in the GNU.  One of SA’s most enduring political figures.",
  "Mzwanele Nyhontso": "Leader of the Pan Africanist Congress of Azania.",
  "Fadiel Adams": "Leader of the National Coloured Congress and founder of the Gatvol Capetonian movement.",
  "Blade Nzimande": "General Secretary of the South African Communist Party and a cabinet minister.",
  "Mzwanele Manyi": "Leader of United Africans Transformation and a former government spin doctor linked to the Gupta family.",
  "Jack Miller": "Leader of the Cape Independence Party.",
  "Strike Thokoane": "Leader of the Azanian People’s Organisation.",
  "Patrick Pillay": "Leader of the Democratic Liberal Congress.",
  "Shameen Thakur-Rajbansi": "Leader of the Minority Front.  The party has been run by the Rajbansi family for decades.",
  "Jeffrey Donson": "Leader of the Independent Civic Organisation of SA.",
  "Themba Godi": "Leader of the African People’s Convention.",
  "Neil de Beer": "Leader of the United Independent Movement.",
  "Mampuru Mampuru": "Leader of the Forum for Service Delivery.",
  "Dumisani Makhanya": "Leader of the Abantu Batho Congress.",
  "Mandla Galo": "Leader of the African Independent Congress.",
  "Mosiuoa Lekota": "Leader of the Congress of the People.  A former ANC stalwart and anti‑Zuma figure.",
  "Julius Nsingwane": "Leader of the Power of Africans Unity.",
  "Makhosandile Ndzuzo": "Leader of the African Democratic Change.",
  "Steve Biko": "A legendary anti‑apartheid activist and founder of the Black Consciousness Movement.  He died in police custody in 1977.",
  "Robert Sobukwe": "The founder of the Pan Africanist Congress.  One of the most brilliant political minds of the liberation struggle.",
  "Nelson Mandela": "The first democratically elected President of South Africa and the most iconic figure of the anti‑apartheid struggle.",
  "FW de Klerk": "The last apartheid President who unbanned the ANC and negotiated the transition to democracy.",
  "Thabo Mbeki": "Former President of South Africa (1999–2008) and successor to Mandela.  His AIDS denialism is estimated to have cost 330,000 lives.",

  /* ── Historical Events & Concepts ── */
  "July 2021 unrest": "A wave of civil unrest in July 2021, primarily in KwaZulu‑Natal and Gauteng, triggered by Jacob Zuma’s imprisonment.  354 people died and R50 billion in damage was caused.",
  "Sharpeville massacre": "The killing of 69 protesters by police on 21 March 1960 during a peaceful anti‑pass march organised by the PAC.",
  "Soweto uprising": "A series of protests led by black schoolchildren in 1976 against the introduction of Afrikaans as a medium of instruction in schools.",
  "Rivonia Trial": "The trial that led to Nelson Mandela and others being sentenced to life imprisonment in 1964.",
  "Freedom Charter": "A document adopted in 1955 at Kliptown, outlining the core principles of the anti‑apartheid struggle and later forming the basis of the Constitution.",
  "Defiance Campaign": "A mass civil disobedience campaign against apartheid laws launched by the ANC in 1952.",
  "Fees Must Fall": "A student‑led protest movement that began in 2015, calling for free, decolonised tertiary education.",
  "Rhodes Must Fall": "A protest movement that began at UCT in 2015, calling for the removal of the statue of Cecil John Rhodes and the decolonisation of education.",
  "1913 Natives Land Act": "Legislation that allocated only 7% of land to the black majority, forming the foundation of apartheid spatial planning.",
  "1956 Women’s March": "A march of approximately 20,000 women to the Union Buildings in Pretoria to protest the extension of pass laws to women.",
  "pass laws": "A system of internal passport control designed to restrict the movement of black people during apartheid.",
  "Group Areas Act": "Apartheid legislation that enforced residential segregation by race.",
  "Population Registration Act": "Apartheid legislation that classified all South Africans by race.",
  "Bantu Education Act": "Apartheid legislation that created a separate and inferior education system for black South Africans.",
  "homeland system": "The apartheid policy of confining black South Africans to designated, often impoverished, 'homelands' or Bantustans.",
  "necklacing": "A brutal method of execution used during the anti‑apartheid struggle, in which a petrol‑filled tyre was placed around a victim’s neck and set alight.",
  "Arms Deal corruption": "A scandal involving bribery and corruption related to South Africa’s 1999 defence procurement package, which has implicated senior ANC figures.",
  "VBS Mutual Bank": "A bank that served poor rural communities in Limpopo and Venda, which collapsed in 2018 after R2 billion was looted by politicians and executives.",
  "Phala Phala scandal": "A controversy involving President Ramaphosa and the theft of $580,000 in US dollars hidden in furniture on his game farm in 2020, which was never reported to police.",
  "Nkandla": "A scandal over the use of R246 million in state funds for security upgrades to Jacob Zuma’s private residence, which led to a Constitutional Court ruling that Zuma had violated the Constitution.",
  "Zuma Must Fall": "A campaign calling for the resignation of Jacob Zuma, marked by mass protests.",
  "Gupta family": "A wealthy business family with close ties to Jacob Zuma, implicated in systemic State Capture as detailed by the Zondo Commission.",
  "Koeberg": "South Africa’s only nuclear power plant, located near Cape Town.",
  "Medupi and Kusile": "Two massive, over‑budget, and delayed coal‑fired power stations built by Eskom, symbolic of the SOE’s challenges."
};