/* ── VERITAS Ideology Database ── */
window.VERITAS_IDEOLOGIES = {
  // ═══════════════════════════════════════════
  // AUTHORITARIAN LEFT (Red)
  // ═══════════════════════════════════════════
  'stalinism': {
    title: 'Stalinism',
    tagline: 'Total state control of the economy and society under a single vanguard party.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Advocates for complete nationalisation of all industry, collectivised agriculture, and suppression of political dissent. The state directs all economic and social life.',
    relevance: 'In SA, this ideology underpins calls for full state ownership of mines, banks, and land, with no compensation. The EFF\'s Marxist-Leninist faction draws from this tradition.',
    tradeoffs: '<strong>Pros:</strong> Rapid industrialisation and elimination of class distinctions.<br><strong>Cons:</strong> Massive human rights abuses, economic inefficiency, and bureaucratic stagnation.',
    whyYouBelong: 'Your answers indicate you consistently support extreme state intervention, centralised planning, and the suppression of opposition for collective goals.',
    historical: 'Soviet Union under Stalin, Maoist China, North Korea.',
    saManifestation: 'EFF radical wing, SACP hardliners. Policies like blanket nationalisation without compensation.',
    metrics: { econIntervention: 10, individualAutonomy: 1, stability: 'LOW' }
  },
  'maoism': {
    title: 'Maoism',
    tagline: 'Peasant-led revolution, continuous class struggle, and cultural transformation.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Emphasises the role of the peasantry in revolution, permanent class struggle, and the remaking of culture and society under a communist party.',
    relevance: 'Inspires radical land reform movements and anti-imperialist rhetoric in SA, particularly around expropriation without compensation and decolonisation.',
    tradeoffs: '<strong>Pros:</strong> Mobilises rural populations and challenges entrenched elites.<br><strong>Cons:</strong> Often leads to famine, cultural destruction, and totalitarian control.',
    whyYouBelong: 'You favour radical redistribution and anti‑imperialist struggle, with a willingness to use state power to transform society fundamentally.',
    historical: 'China under Mao, Peru\'s Shining Path, Nepal\'s Maoist insurgency.',
    saManifestation: 'Radical land activists, some EFF and MKP rhetoric on land and economic justice.',
    metrics: { econIntervention: 10, individualAutonomy: 1, stability: 'LOW' }
  },
  'leninism': {
    title: 'Leninism',
    tagline: 'A vanguard party leads the working class to revolution and establishes a dictatorship of the proletariat.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Advocates for a disciplined, professional revolutionary party to seize state power and then use it to suppress counter-revolution and build socialism.',
    relevance: 'The SACP and elements within the EFF draw on Leninist organisational principles, emphasising democratic centralism and a vanguard role.',
    tradeoffs: '<strong>Pros:</strong> Provides a clear strategy for revolutionary change.<br><strong>Cons:</strong> Concentrates power in a small elite, often leading to authoritarianism.',
    whyYouBelong: 'You support a strong, centralised party leading transformation, with a focus on class struggle and the overthrow of existing power structures.',
    historical: 'Bolshevik Revolution, early Soviet Union, Cuba under Castro.',
    saManifestation: 'SACP, EFF internal structure, elements of the Tripartite Alliance.',
    metrics: { econIntervention: 9, individualAutonomy: 2, stability: 'LOW' }
  },
  'marxism-leninism': {
    title: 'Marxism-Leninism',
    tagline: 'The synthesis of Marx\'s economics and Lenin\'s revolutionary praxis.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'The official ideology of many communist states, combining Marxist analysis of capitalism with Leninist tactics of revolution and party organisation.',
    relevance: 'The EFF\'s constitution and public statements explicitly reference Marxism-Leninism, and the SACP remains a Marxist-Leninist party.',
    tradeoffs: '<strong>Pros:</strong> Provides a comprehensive framework for understanding and changing society.<br><strong>Cons:</strong> Historically associated with single‑party rule, repression, and economic mismanagement.',
    whyYouBelong: 'You identify with the intellectual tradition of Marx and the revolutionary practice of Lenin, seeking a complete transformation of the economic base.',
    historical: 'Soviet Union, China (pre‑market reforms), Cuba, Vietnam.',
    saManifestation: 'EFF, SACP. Nationalisation, land reform, anti‑imperialism.',
    metrics: { econIntervention: 9, individualAutonomy: 2, stability: 'LOW' }
  },
  'trotskyism': {
    title: 'Trotskyism',
    tagline: 'Permanent revolution and international socialism, opposing Stalinist bureaucracy.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Critiques the Soviet Union as a degenerated workers\' state, advocating for continuous revolution across borders and genuine workers\' democracy.',
    relevance: 'Small but vocal Trotskyist groups exist within SA labour movements, such as the Workers and Socialist Party (WASP).',
    tradeoffs: '<strong>Pros:</strong> Maintains a critique of authoritarian socialism and emphasises international solidarity.<br><strong>Cons:</strong> Historically marginal and often faction-ridden.',
    whyYouBelong: 'You are a leftist who rejects Stalinist bureaucracy and believes revolution must be global and democratic in its internal structures.',
    historical: 'Leon Trotsky, Fourth International, various small parties worldwide.',
    saManifestation: 'WASP, elements within COSATU and student movements.',
    metrics: { econIntervention: 8, individualAutonomy: 3, stability: 'LOW' }
  },
  'national-bolshevism': {
    title: 'National Bolshevism',
    tagline: 'A fusion of radical socialism and ultranationalism.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Combines communist economics with nationalist, often xenophobic, rhetoric. Rejects internationalism in favour of national purity.',
    relevance: 'Some fringe groups in SA have attempted to blend left economics with anti‑immigrant sentiment, though this is not mainstream.',
    tradeoffs: '<strong>Pros:</strong> Can mobilise nationalist sentiment for economic redistribution.<br><strong>Cons:</strong> Often descends into racism and authoritarianism.',
    whyYouBelong: 'Your answers suggest a blend of left‑wing economic policy with strong nationalist, possibly exclusionary, instincts.',
    historical: 'Early Nazi Party (Strasserite wing), modern Russian National Bolshevik Party.',
    saManifestation: 'Fringe groups, some elements of anti‑immigrant populism with left economics.',
    metrics: { econIntervention: 8, individualAutonomy: 2, stability: 'LOW' }
  },
  'mugabeism': {
    title: 'Mugabeism',
    tagline: 'Radical resource reclamation, anti‑imperialism, and strong executive authority.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Named after Zimbabwe\'s Robert Mugabe, this ideology advocates fast‑tracked land reform, nationalisation of key industries, and Pan‑Africanist rhetoric, often combined with authoritarian governance.',
    relevance: 'Directly influences conversations in SA around aggressive land expropriation without compensation and the rejection of Western institutions.',
    tradeoffs: '<strong>Pros:</strong> Rapidly disrupts colonial-era ownership patterns and empowers previously dispossessed groups.<br><strong>Cons:</strong> High risk of economic collapse, capital flight, and institutional breakdown.',
    whyYouBelong: 'You support radical land reform and state‑led economic transformation, even at the risk of economic stability and democratic norms.',
    historical: 'Zimbabwe under Mugabe, Venezuela under Chávez/Maduro.',
    saManifestation: 'EFF land policy, MK Party rhetoric on resource nationalism and traditional authority.',
    metrics: { econIntervention: 9, individualAutonomy: 3, stability: 'LOW' }
  },
  'chavism': {
    title: 'Chavism',
    tagline: 'Socialist populism fuelled by resource nationalism and charismatic leadership.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Uses oil or mineral wealth to fund extensive social programmes while consolidating power in a central executive. Emphasises anti‑Americanism and South‑South solidarity.',
    relevance: 'The EFF\'s rhetoric around nationalisation of mines and banks, combined with a strong central leader, mirrors Chavist models.',
    tradeoffs: '<strong>Pros:</strong> Rapid poverty reduction and mass mobilisation of the poor.<br><strong>Cons:</strong> Economic dependency on commodities, hyperinflation, and erosion of democratic institutions.',
    whyYouBelong: 'You favour a charismatic leader using resource wealth for the poor, with scepticism toward Western powers and market mechanisms.',
    historical: 'Venezuela under Hugo Chávez, Bolivia under Evo Morales.',
    saManifestation: 'EFF, some ANC factions. Nationalisation, social grants, anti‑imperialist foreign policy.',
    metrics: { econIntervention: 8, individualAutonomy: 3, stability: 'LOW' }
  },
  'state-capitalism': {
    title: 'State Capitalism',
    tagline: 'The state acts as the primary capitalist, owning and operating key industries.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Rather than abolishing capitalism, the state becomes the dominant market player. SOEs are used to drive development and maintain political control.',
    relevance: 'South Africa\'s extensive SOE network (Eskom, Transnet) and the debate over their privatisation or reform is a state‑capitalist versus market debate.',
    tradeoffs: '<strong>Pros:</strong> Can direct investment to national priorities and maintain employment.<br><strong>Cons:</strong> Often leads to corruption, inefficiency, and political interference.',
    whyYouBelong: 'You believe the state should own and run key industries, using them for developmental goals rather than private profit.',
    historical: 'China (post‑1978), Singapore, South Africa\'s apartheid‑era parastatals.',
    saManifestation: 'Defence of SOEs, ANC policy on state‑led development, opposition to privatisation.',
    metrics: { econIntervention: 7, individualAutonomy: 4, stability: 'MODERATE' }
  },
  'left-populism': {
    title: 'Left Populism',
    tagline: 'Mobilising "the people" against elites, with redistributive economic policies.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Frames politics as a struggle between the ordinary people and a corrupt elite, advocating for wealth redistribution, expanded social programmes, and nationalist economics.',
    relevance: 'Julius Malema\'s EFF and Jacob Zuma\'s MKP both employ left‑populist rhetoric, targeting "white monopoly capital" and promising radical economic transformation.',
    tradeoffs: '<strong>Pros:</strong> Can energise disenfranchised voters and force economic justice onto the agenda.<br><strong>Cons:</strong> Often relies on charismatic leaders, oversimplifies complex issues, and can undermine institutions.',
    whyYouBelong: 'You respond to rhetoric that pits ordinary people against a corrupt elite, and you support strong state action to redistribute wealth.',
    historical: 'Latin American populism, early ANC Youth League under Malema.',
    saManifestation: 'EFF, MKP, some ANC factions. Anti‑elite rhetoric, nationalisation promises.',
    metrics: { econIntervention: 7, individualAutonomy: 4, stability: 'MODERATE-LOW' }
  },
  'agrarianism': {
    title: 'Agrarianism',
    tagline: 'A society built on the independent farmer, with land as the foundation of liberty.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Prioritises agricultural life and land ownership for all citizens, often sceptical of urbanisation and industrial capitalism. Can be left or right depending on context.',
    relevance: 'Land reform in SA, particularly the "willing buyer, willing seller" model and calls for expropriation, taps into agrarian ideals of land‑based dignity.',
    tradeoffs: '<strong>Pros:</strong> Emphasises self‑sufficiency, community, and connection to the land.<br><strong>Cons:</strong> Can be economically inefficient at scale and resistant to modernisation.',
    whyYouBelong: 'You see land ownership as central to freedom and dignity, and you support policies that return land to the people who work it.',
    historical: 'Jeffersonian democracy, Russian Narodniks, African land reform movements.',
    saManifestation: 'Land reform policy, EFF\'s land expropriation stance, rural development programmes.',
    metrics: { econIntervention: 6, individualAutonomy: 5, stability: 'MODERATE' }
  },
  'conservative-socialism': {
    title: 'Conservative Socialism',
    tagline: 'Socialist economics paired with traditional social values.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'Advocates for state ownership and redistribution while maintaining conservative positions on family, religion, and cultural issues. Often associated with religious socialism.',
    relevance: 'Some African Christian movements and the ATM blend left economics with social conservatism, opposing LGBTQ+ rights while supporting economic transformation.',
    tradeoffs: '<strong>Pros:</strong> Can appeal to religious communities while addressing economic inequality.<br><strong>Cons:</strong> Creates tension between economic liberation and social conservatism.',
    whyYouBelong: 'You want the state to redistribute wealth but also to uphold traditional moral values and cultural norms.',
    historical: 'Christian socialism in Europe, some strands of African socialism.',
    saManifestation: 'ATM, some ACDP factions, elements of the Shembe Church\'s political engagement.',
    metrics: { econIntervention: 7, individualAutonomy: 3, stability: 'MODERATE' }
  },
  'juche': {
    title: 'Juche',
    tagline: 'Self‑reliance, national independence, and supreme leadership.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'The official ideology of North Korea, emphasising political, economic, and military self‑sufficiency under a single, absolute leader.',
    relevance: 'Minimal direct influence in SA, but the rhetoric of economic independence and anti‑imperialism resonates with some Pan‑Africanist and anti‑Western discourse.',
    tradeoffs: '<strong>Pros:</strong> Extreme national sovereignty and independence from foreign influence.<br><strong>Cons:</strong> Leads to totalitarianism, extreme poverty, and international isolation.',
    whyYouBelong: 'Your answers indicate a strong preference for complete national self‑reliance and a willingness to accept centralised, even absolute, leadership.',
    historical: 'North Korea since its founding.',
    saManifestation: 'Fringe groups; not a mainstream SA ideology.',
    metrics: { econIntervention: 10, individualAutonomy: 1, stability: 'LOW' }
  },

  // ═══════════════════════════════════════════
  // AUTHORITARIAN RIGHT (Blue)
  // ═══════════════════════════════════════════
  'fascism': {
    title: 'Fascism',
    tagline: 'Ultranationalist, authoritarian, and corporatist state control.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Rejects both liberal democracy and socialism, promoting a totalitarian state led by a single leader, with a mixed economy controlled by the state in partnership with business.',
    relevance: 'No major SA party advocates fascism, but the term is often used polemically. The ideology\'s emphasis on national purity and strong leadership has echoes in far‑right fringe groups.',
    tradeoffs: '<strong>Pros:</strong> Can rapidly mobilise a nation for war or industrialisation.<br><strong>Cons:</strong> Inevitably leads to oppression, genocide, and catastrophic war.',
    whyYouBelong: 'Your answers suggest extreme nationalism, a willingness to sacrifice democratic norms for order, and a preference for a strong, unchallenged leader.',
    historical: 'Mussolini\'s Italy, Hitler\'s Germany, Franco\'s Spain.',
    saManifestation: 'Fringe far‑right groups; not a mainstream SA ideology.',
    metrics: { econIntervention: 6, individualAutonomy: 1, stability: 'LOW' }
  },
  'neo-fascism': {
    title: 'Neo-Fascism',
    tagline: 'Modernised ultranationalism with populist rhetoric against immigrants and elites.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Updates fascist ideology for the contemporary era, often using democratic processes to gain power before dismantling them. Emphasises nativism, law and order, and cultural purity.',
    relevance: 'Some anti‑immigrant movements in SA, such as Operation Dudula, have been compared to neo‑fascist tendencies, though they lack the full ideological apparatus.',
    tradeoffs: '<strong>Pros:</strong> Can tap into genuine grievances about crime and unemployment.<br><strong>Cons:</strong> Promotes xenophobia, erodes democratic institutions, and scapegoats vulnerable groups.',
    whyYouBelong: 'You respond strongly to anti‑immigrant messaging and law‑and‑order rhetoric, and you are willing to empower the state to enforce cultural and national purity.',
    historical: 'Modern far‑right parties in Europe, some Trumpist factions in the US.',
    saManifestation: 'Operation Dudula, some PA and ActionSA rhetoric on immigration.',
    metrics: { econIntervention: 5, individualAutonomy: 2, stability: 'LOW' }
  },
  'nazism': {
    title: 'Nazism',
    tagline: 'Racial hierarchy, Aryan supremacy, and total state control.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'The specific ideology of Hitler\'s Germany, combining extreme racism, eugenics, anti‑Semitism, and territorial expansion with a totalitarian state and a war economy.',
    relevance: 'No SA party advocates Nazism. The ideology is historically associated with the apartheid regime\'s racial theories, though apartheid was distinct.',
    tradeoffs: '<strong>Pros:</strong> None — universally condemned as a crime against humanity.<br><strong>Cons:</strong> Genocide, world war, and total moral collapse.',
    whyYouBelong: 'Your answers indicate an extreme belief in racial hierarchy and a willingness to use state violence to enforce it.',
    historical: 'Nazi Germany, 1933‑1945.',
    saManifestation: 'Not present in SA politics; historical associations with apartheid racial ideology.',
    metrics: { econIntervention: 7, individualAutonomy: 1, stability: 'LOW' }
  },
  'islamist-theocracy': {
    title: 'Islamist Theocracy',
    tagline: 'Governance by Islamic law under clerical authority.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Seeks to establish a state governed by Sharia law, with religious leaders holding ultimate political authority. Ranges from conservative monarchies to revolutionary republics.',
    relevance: 'Al Jama‑ah advocates for Muslim personal law and Islamic values in public life, though they operate within the constitutional framework. Full theocracy has no mainstream SA support.',
    tradeoffs: '<strong>Pros:</strong> Provides moral and legal framework for Muslim communities.<br><strong>Cons:</strong> Conflicts with secular constitutionalism and the rights of non‑Muslims and women.',
    whyYouBelong: 'You believe religious law should govern public life and that the state should enforce religious morality.',
    historical: 'Iran since 1979, Saudi Arabia, Taliban‑ruled Afghanistan.',
    saManifestation: 'Al Jama‑ah (constitutional), fringe Islamist groups.',
    metrics: { econIntervention: 5, individualAutonomy: 2, stability: 'MODERATE' }
  },
  'christian-theocracy': {
    title: 'Christian Theocracy',
    tagline: 'Governance by biblical law under church authority.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Seeks to base civil law on Christian scripture, often opposing secularism, abortion, same‑sex marriage, and other practices deemed un‑Christian.',
    relevance: 'The ACDP supports Christian values in public policy and has advocated for the death penalty and against LGBTQ+ rights, though within a democratic framework.',
    tradeoffs: '<strong>Pros:</strong> Provides a clear moral compass rooted in a long religious tradition.<br><strong>Cons:</strong> Conflicts with SA\'s secular Constitution, particularly on gender and sexuality rights.',
    whyYouBelong: 'You believe the state should be guided by Christian principles, even if that means limiting the rights of those who do not share your faith.',
    historical: 'Medieval Europe, Vatican City, some conservative Christian movements in Africa.',
    saManifestation: 'ACDP, some religious lobbying groups.',
    metrics: { econIntervention: 4, individualAutonomy: 2, stability: 'MODERATE' }
  },
  'hindu-nationalism': {
    title: 'Hindu Nationalism',
    tagline: 'India as a Hindu nation, with cultural and religious primacy.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Advocates for the dominance of Hindu culture and religion in national identity, often at the expense of Muslim and other minority rights.',
    relevance: 'Limited direct SA relevance, though the Indian diaspora includes supporters of the BJP and its ideology.',
    tradeoffs: '<strong>Pros:</strong> Can mobilise a sense of national pride and cultural unity.<br><strong>Cons:</strong> Marginalises religious minorities and can lead to sectarian violence.',
    whyYouBelong: 'You strongly identify with your religious community and believe the state should reflect its values and protect its primacy.',
    historical: 'RSS and BJP in India, Hindutva movement.',
    saManifestation: 'Diaspora politics; not a significant SA party platform.',
    metrics: { econIntervention: 5, individualAutonomy: 3, stability: 'MODERATE' }
  },
  'colonialism': {
    title: 'Colonialism',
    tagline: 'Direct rule by a foreign power for economic exploitation.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'The historical practice of European powers controlling African territories for resource extraction, justified by racist ideologies of superiority.',
    relevance: 'SA\'s history is defined by colonialism and its legacies. No party advocates a return to colonial rule, but debates about land, reparations, and identity are its direct consequences.',
    tradeoffs: '<strong>Pros:</strong> None for the colonised — it is a system of oppression.<br><strong>Cons:</strong> Genocide, enslavement, cultural destruction, and permanent underdevelopment.',
    whyYouBelong: 'Your answers are unlikely to align with this ideology in a modern context; it is included for historical completeness.',
    historical: 'British, Dutch, French, and Portuguese empires in Africa.',
    saManifestation: 'Not a current political platform; its legacy shapes all SA politics.',
    metrics: { econIntervention: 8, individualAutonomy: 1, stability: 'LOW' }
  },
  'imperialism': {
    title: 'Imperialism',
    tagline: 'Extending a nation\'s power through diplomacy or military force.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'The policy of extending a country\'s influence through colonisation, military force, or economic dominance. Often justified by a sense of cultural or racial superiority.',
    relevance: 'SA\'s foreign policy debates — such as participation in BRICS, relations with the West, and military intervention in Africa — are shaped by anti‑imperialist sentiment.',
    tradeoffs: '<strong>Pros:</strong> Can enrich the imperial power and spread its culture.<br><strong>Cons:</strong> Oppresses colonised peoples, causes wars, and creates lasting global inequalities.',
    whyYouBelong: 'You may support a strong national projection of power abroad, or you may strongly oppose it — the ideology itself is included for contextual understanding.',
    historical: 'British, French, and American empires.',
    saManifestation: 'Anti‑imperialist rhetoric is common across SA parties, particularly on the left.',
    metrics: { econIntervention: 7, individualAutonomy: 2, stability: 'LOW' }
  },
  'aristocracy': {
    title: 'Aristocracy',
    tagline: 'Rule by a hereditary elite based on birth and land ownership.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'A system where power is held by a small, privileged ruling class, often justified by tradition and lineage.',
    relevance: 'Traditional leadership in SA, such as the Zulu monarchy and various chiefs, retains elements of aristocratic authority, recognised by the Constitution.',
    tradeoffs: '<strong>Pros:</strong> Provides continuity and cultural preservation.<br><strong>Cons:</strong> Conflicts with democratic principles and can entrench inequality.',
    whyYouBelong: 'You respect traditional hierarchies and believe that those born into leadership roles should retain authority.',
    historical: 'European monarchies, pre‑colonial African kingdoms.',
    saManifestation: 'Traditional leaders, IFP and MKP support for the Zulu monarchy, Ingonyama Trust.',
    metrics: { econIntervention: 3, individualAutonomy: 3, stability: 'MODERATE-HIGH' }
  },
  'paleo-conservatism': {
    title: 'Paleo-Conservatism',
    tagline: 'Traditional values, limited government, and national sovereignty.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Emphasises cultural conservatism, opposition to immigration, and a non‑interventionist foreign policy, combined with scepticism of global capitalism.',
    relevance: 'The FF+ and some factions within the DA draw on paleo‑conservative ideas around cultural preservation and national identity.',
    tradeoffs: '<strong>Pros:</strong> Protects cultural heritage and national identity.<br><strong>Cons:</strong> Can be isolationist and resistant to necessary social change.',
    whyYouBelong: 'You value tradition, national identity, and cultural continuity, and you are sceptical of rapid social transformation and globalisation.',
    historical: 'Old Right in the US, European traditionalists.',
    saManifestation: 'FF+, conservative Afrikaner movements, some IFP traditionalists.',
    metrics: { econIntervention: 4, individualAutonomy: 4, stability: 'MODERATE' }
  },
  'neo-conservatism': {
    title: 'Neo-Conservatism',
    tagline: 'Free markets, strong military, and the promotion of democracy abroad.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Advocates for an assertive foreign policy to spread democratic values, combined with domestic free‑market economics and traditional social values.',
    relevance: 'Some DA foreign policy positions, particularly regarding human rights and opposition to authoritarian regimes, align with neo‑conservative thinking.',
    tradeoffs: '<strong>Pros:</strong> Can promote human rights and challenge dictatorships.<br><strong>Cons:</strong> Often leads to military intervention and is seen as hypocritical or imperialist.',
    whyYouBelong: 'You support a strong national defence, the promotion of democratic values abroad, and free‑market economics at home.',
    historical: 'Reagan and Bush administrations in the US, Blair\'s foreign policy.',
    saManifestation: 'DA foreign policy, some ActionSA rhetoric.',
    metrics: { econIntervention: 3, individualAutonomy: 5, stability: 'MODERATE' }
  },
  'authoritarian-capitalism': {
    title: 'Authoritarian Capitalism',
    tagline: 'Free markets enforced by a powerful, often repressive state.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'The state maintains strict political control while allowing or encouraging capitalist economic activity. Common in East Asian developmental states.',
    relevance: 'Some critics argue that SA under the ANC exhibits elements of this, with a politically connected elite enriching itself while the state maintains control over dissent.',
    tradeoffs: '<strong>Pros:</strong> Can produce rapid economic growth and stability.<br><strong>Cons:</strong> Suppresses political freedom and often leads to crony capitalism.',
    whyYouBelong: 'You prioritise economic growth and order over political freedom, and you are comfortable with a strong state that enforces market discipline.',
    historical: 'Singapore, China (economic liberalisation), Chile under Pinochet.',
    saManifestation: 'Critique of ANC economic policy, state capture era.',
    metrics: { econIntervention: 4, individualAutonomy: 3, stability: 'HIGH' }
  },
  'corporate-autocracy': {
    title: 'Corporate Autocracy',
    tagline: 'Rule by or in close alliance with large corporations.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Political power is concentrated in the hands of corporate executives and their allies, with the state serving business interests rather than the public.',
    relevance: 'The Zondo Commission exposed elements of corporate capture of the state, where private interests dictated policy through corrupt relationships.',
    tradeoffs: '<strong>Pros:</strong> Can create a stable environment for business.<br><strong>Cons:</strong> Erodes democracy, entrenches inequality, and serves the wealthy at the expense of the majority.',
    whyYouBelong: 'Your answers suggest you believe that business leaders and corporate interests should have significant influence over government policy.',
    historical: 'Russia under oligarchs, some post‑Soviet states.',
    saManifestation: 'State capture era, Gupta‑linked networks, critique of "white monopoly capital".',
    metrics: { econIntervention: 2, individualAutonomy: 3, stability: 'MODERATE' }
  },
  'monarchism': {
    title: 'Monarchism',
    tagline: 'Rule by a hereditary monarch with varying degrees of power.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Advocates for a king or queen as head of state, ranging from absolute monarchy to constitutional monarchy.',
    relevance: 'The Zulu monarchy and other traditional kingdoms in SA embody monarchical principles, recognised but subordinated to the Constitution.',
    tradeoffs: '<strong>Pros:</strong> Provides national unity and continuity.<br><strong>Cons:</strong> Conflicts with democratic egalitarianism and can entrench privilege.',
    whyYouBelong: 'You respect the symbolic and cultural role of a monarch and believe hereditary leadership has a place in modern governance.',
    historical: 'United Kingdom, Saudi Arabia, historical African kingdoms.',
    saManifestation: 'Zulu monarchy, Ingonyama Trust, IFP and MKP support for traditional leaders.',
    metrics: { econIntervention: 3, individualAutonomy: 3, stability: 'MODERATE-HIGH' }
  },
  'kleptocracy': {
    title: 'Kleptocracy',
    tagline: 'Rule by thieves — the state is a vehicle for personal enrichment.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'A system where corruption is institutionalised, and those in power use the state to steal public resources for themselves and their allies.',
    relevance: 'The Zondo Commission detailed how SA under Zuma became, in significant part, a kleptocracy. This is a warning, not a prescription.',
    tradeoffs: '<strong>Pros:</strong> None for the public — it is a form of organised crime at the state level.<br><strong>Cons:</strong> Destroys institutions, impoverishes the population, and undermines the rule of law.',
    whyYouBelong: 'Your answers are unlikely to align with this as a positive ideology; it is included as a diagnostic category.',
    historical: 'Mobutu\'s Zaire, Abacha\'s Nigeria, modern Russia.',
    saManifestation: 'State capture era, Zuma administration, Gupta family.',
    metrics: { econIntervention: 2, individualAutonomy: 2, stability: 'LOW' }
  },
  'military-junta': {
    title: 'Military Junta',
    tagline: 'Government by a committee of military leaders.',
    quadrant: 'AUTHORITARIAN RIGHT',
    summary: 'Power is seized and held by the armed forces, often justifying their rule as necessary for national stability and security.',
    relevance: 'SA has a history of military rule in neighbouring states (e.g., Zimbabwe\'s early years, Lesotho interventions). The SANDF is constitutionally subordinate to civilian authority.',
    tradeoffs: '<strong>Pros:</strong> Can restore order in times of extreme chaos.<br><strong>Cons:</strong> Suppresses democracy, human rights, and civilian governance.',
    whyYouBelong: 'You may believe the military should play a greater role in maintaining order and national security, even at the expense of civilian rule.',
    historical: 'Myanmar, Egypt under Sisi, various Latin American and African regimes.',
    saManifestation: 'Not a current SA political platform; historical concerns during transition.',
    metrics: { econIntervention: 5, individualAutonomy: 1, stability: 'LOW' }
  },

  // ═══════════════════════════════════════════
  // LIBERTARIAN LEFT (Green)
  // ═══════════════════════════════════════════
  'anarcho-communism': {
    title: 'Anarcho-Communism',
    tagline: 'A stateless, classless, moneyless society of freely associated communes.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Seeks to abolish both the state and capitalism, replacing them with decentralised, self‑governing communities based on mutual aid and common ownership.',
    relevance: 'Minimal direct influence in SA, but elements of anarchist thought appear in some student and community movements, particularly around mutual aid and anti‑state activism.',
    tradeoffs: '<strong>Pros:</strong> Radical freedom and equality.<br><strong>Cons:</strong> Lacks a clear transition strategy and has never been implemented at scale.',
    whyYouBelong: 'You reject both state authority and capitalist markets, believing in the capacity of ordinary people to organise themselves without coercion.',
    historical: 'Revolutionary Catalonia, Makhnovist Ukraine, Zapatista communities.',
    saManifestation: 'Some community mutual aid groups, anarchist collectives, student movements.',
    metrics: { econIntervention: 10, individualAutonomy: 10, stability: 'LOW' }
  },
  'eco-anarchism': {
    title: 'Eco-Anarchism',
    tagline: 'A stateless society living in harmony with nature.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Combines anarchist rejection of hierarchy with deep ecological principles, advocating for small‑scale, sustainable communities and opposition to industrial civilisation.',
    relevance: 'Environmental activism in SA, such as anti‑fracking and anti‑nuclear movements, sometimes draws on eco‑anarchist ideas about local autonomy and ecological stewardship.',
    tradeoffs: '<strong>Pros:</strong> Prioritises ecological sustainability and local self‑determination.<br><strong>Cons:</strong> Difficult to implement at scale in a modern economy.',
    whyYouBelong: 'You prioritise environmental protection and local community control over both state and corporate power.',
    historical: 'Green anarchist movements, Earth First!, some indigenous resistance movements.',
    saManifestation: 'Anti‑fracking activism, community environmental groups, some GOOD Party rhetoric.',
    metrics: { econIntervention: 6, individualAutonomy: 10, stability: 'LOW' }
  },
  'council-communism': {
    title: 'Council Communism',
    tagline: 'Workers\' councils as the basis of a stateless communist society.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Rejects the vanguard party model, arguing that workers themselves, organised in councils, should manage production and social life without a separate state apparatus.',
    relevance: 'South Africa\'s strong trade union movement, particularly COSATU\'s history of shop‑floor democracy, contains echoes of council communist ideas.',
    tradeoffs: '<strong>Pros:</strong> Genuine workers\' democracy and self‑management.<br><strong>Cons:</strong> Historically marginalised by Leninist and social‑democratic movements.',
    whyYouBelong: 'You believe in direct workers\' control of industry and reject both capitalist management and state bureaucracy.',
    historical: 'German Revolution of 1918‑19, early Soviet soviets (before Bolshevik consolidation), Hungarian Revolution of 1956.',
    saManifestation: 'COSATU\'s democratic traditions, some left‑wing union factions.',
    metrics: { econIntervention: 9, individualAutonomy: 8, stability: 'LOW' }
  },
  'democratic-socialism': {
    title: 'Democratic Socialism',
    tagline: 'Socialism achieved through democratic means, not revolution.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Advocates for the gradual, democratic transformation of capitalism into socialism, with extensive public ownership, strong unions, and a robust welfare state.',
    relevance: 'The SACP, while Marxist‑Leninist in theory, in practice operates within a democratic framework. Many ANC and COSATU members are effectively democratic socialists.',
    tradeoffs: '<strong>Pros:</strong> Reduces inequality while maintaining political freedom.<br><strong>Cons:</strong> Can be slow to achieve change and depends on a functional democratic state.',
    whyYouBelong: 'You want significant state intervention in the economy and redistribution of wealth, but you value democratic processes and individual rights.',
    historical: 'Western European socialist parties, early Israeli kibbutzim, Allende\'s Chile.',
    saManifestation: 'ANC left, SACP, COSATU, RISE Mzansi, GOOD.',
    metrics: { econIntervention: 8, individualAutonomy: 7, stability: 'MODERATE-HIGH' }
  },
  'social-democracy': {
    title: 'Social Democracy',
    tagline: 'A robust welfare state protected inside a democratic market economy.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Seeks to civilise capitalism through regulation, redistribution, and universal public services, without abolishing private property or markets.',
    relevance: 'The dominant ideology of the ANC\'s moderate wing and the basis for SA\'s social grant system, NHI proposals, and labour legislation.',
    tradeoffs: '<strong>Pros:</strong> Substantially reduces poverty and inequality while maintaining economic growth.<br><strong>Cons:</strong> Requires a highly functional, uncorrupted state to deliver effectively.',
    whyYouBelong: 'You support a mixed economy with strong state intervention to ensure social welfare, but you accept a role for markets and private enterprise.',
    historical: 'Nordic countries, post‑war Britain, Germany\'s social market economy.',
    saManifestation: 'ANC mainstream, RISE Mzansi, GOOD, BOSA (left flank).',
    metrics: { econIntervention: 7, individualAutonomy: 8, stability: 'HIGH' }
  },
  'green-socialism': {
    title: 'Green Socialism',
    tagline: 'Ecological sustainability as the foundation of a socialist economy.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Combines socialist economics with a deep commitment to environmental protection, arguing that capitalism inherently destroys the planet.',
    relevance: 'The GOOD Party and elements of RISE Mzansi incorporate green socialist ideas, advocating for a just transition away from coal and towards renewable energy.',
    tradeoffs: '<strong>Pros:</strong> Addresses both inequality and climate change.<br><strong>Cons:</strong> Can be costly in the short term and disrupt carbon‑dependent communities.',
    whyYouBelong: 'You see environmental destruction and economic inequality as linked crises that must be addressed together through state action.',
    historical: 'German Green Party, global Green New Deal proposals.',
    saManifestation: 'GOOD Party, environmental NGOs, just transition advocacy.',
    metrics: { econIntervention: 7, individualAutonomy: 8, stability: 'MODERATE' }
  },
  'libertarian-socialism': {
    title: 'Libertarian Socialism',
    tagline: 'Socialism without the state — workers\' self‑management and direct democracy.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Rejects both capitalist markets and the authoritarian state, advocating for a federation of self‑managed workplaces and communities.',
    relevance: 'Some community‑based organisations and left‑wing student groups in SA espouse libertarian socialist ideals, particularly around direct action and mutual aid.',
    tradeoffs: '<strong>Pros:</strong> Maximises freedom and equality simultaneously.<br><strong>Cons:</strong> Lacks a clear path to implementation in large, complex societies.',
    whyYouBelong: 'You want a radically democratic and egalitarian society, free from both corporate and state domination.',
    historical: 'Spanish Civil War collectives, Paris Commune, Zapatista autonomous municipalities.',
    saManifestation: 'Small left‑wing groups, community mutual aid networks, some student movements.',
    metrics: { econIntervention: 8, individualAutonomy: 9, stability: 'LOW' }
  },
  'syndicalism': {
    title: 'Syndicalism',
    tagline: 'Trade unions as the building blocks of a new society.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Advocates for the control of industry by trade unions, using direct action such as general strikes to overthrow capitalism and the state.',
    relevance: 'SA\'s powerful trade union movement, particularly COSATU\'s history of mass strikes and political influence, carries syndicalist DNA.',
    tradeoffs: '<strong>Pros:</strong> Builds on existing worker organisations and class consciousness.<br><strong>Cons:</strong> Can be absorbed into party politics and lose its revolutionary edge.',
    whyYouBelong: 'You see trade unions as the most legitimate vehicle for social change and believe workers should directly control the economy.',
    historical: 'French CGT, Spanish CNT, Italian USI.',
    saManifestation: 'COSATU (historically), NUM, NUMSA, SAFTU.',
    metrics: { econIntervention: 9, individualAutonomy: 7, stability: 'LOW' }
  },
  'democratic-confederalism': {
    title: 'Democratic Confederalism',
    tagline: 'A stateless democracy based on local assemblies and gender equality.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Developed by Abdullah Öcalan, this ideology proposes a decentralised, non‑state system of self‑governance through local councils, with strong emphasis on women\'s liberation and ecological sustainability.',
    relevance: 'While not a SA ideology, its principles resonate with some community‑based organisations and feminist movements in SA advocating for decentralised, participatory governance.',
    tradeoffs: '<strong>Pros:</strong> Empowers local communities and promotes gender equality.<br><strong>Cons:</strong> Has only been implemented in war‑torn Rojava; untested in stable contexts.',
    whyYouBelong: 'You favour radical decentralisation, direct democracy, and a strong commitment to gender and ecological justice.',
    historical: 'Rojava (Northern Syria).',
    saManifestation: 'Some feminist and community‑based organisations, not a party platform.',
    metrics: { econIntervention: 6, individualAutonomy: 9, stability: 'LOW' }
  },
  'luxemburgism': {
    title: 'Luxemburgism',
    tagline: 'Revolutionary socialism through mass strikes and spontaneous worker action.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Based on the ideas of Rosa Luxemburg, this ideology critiques both reformist social democracy and Leninist vanguardism, arguing for mass worker democracy and internationalism.',
    relevance: 'Luxemburg\'s critique of imperialism and reformism finds echoes in SA left‑wing circles that reject both the ANC\'s gradualism and the EFF\'s authoritarian tendencies.',
    tradeoffs: '<strong>Pros:</strong> Emphasises workers\' self‑activity and international solidarity.<br><strong>Cons:</strong> Historically outmanoeuvred by Leninist and social‑democratic parties.',
    whyYouBelong: 'You are a revolutionary socialist who values internal party democracy and mass worker participation over centralised leadership.',
    historical: 'Spartacist League, German Revolution of 1918‑19.',
    saManifestation: 'Small left‑wing groups, some COSATU intellectuals.',
    metrics: { econIntervention: 8, individualAutonomy: 8, stability: 'LOW' }
  },
  'progressivism': {
    title: 'Progressivism',
    tagline: 'Social reform, equality, and the expansion of rights.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'A broad movement advocating for social justice, civil rights, environmental protection, and government action to address inequality, operating within a liberal democratic framework.',
    relevance: 'RISE Mzansi, GOOD, and the DA\'s liberal wing all draw on progressive ideas around rights expansion and institutional reform.',
    tradeoffs: '<strong>Pros:</strong> Advances human rights and social justice within existing institutions.<br><strong>Cons:</strong> Can be incremental and insufficient to address deep structural problems.',
    whyYouBelong: 'You support expanding rights, protecting minorities, and using government to address social problems, while respecting democratic processes.',
    historical: 'US Progressive Era, global human rights movements.',
    saManifestation: 'RISE Mzansi, GOOD, BOSA, DA liberal wing.',
    metrics: { econIntervention: 5, individualAutonomy: 8, stability: 'HIGH' }
  },
  'liberal-democracy': {
    title: 'Liberal Democracy (Left‑Leaning)',
    tagline: 'Free elections, individual rights, and a mixed economy.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'The foundational ideology of the SA Constitution, combining political freedom with a commitment to social and economic rights. The state intervenes to correct market failures and protect the vulnerable.',
    relevance: 'The DA\'s constitutionalism, RISE Mzansi\'s technocratic reformism, and GOOD\'s spatial justice agenda all operate within a left‑liberal democratic framework.',
    tradeoffs: '<strong>Pros:</strong> Balances freedom with social responsibility.<br><strong>Cons:</strong> Can be slow to address deep‑rooted inequality.',
    whyYouBelong: 'You believe in free elections, constitutional government, and a market economy tempered by social welfare.',
    historical: 'Post‑war Western Europe, modern Canada, Australia.',
    saManifestation: 'Constitution of SA, DA, RISE Mzansi, BOSA, GOOD.',
    metrics: { econIntervention: 5, individualAutonomy: 8, stability: 'HIGH' }
  },
  'gandhism': {
    title: 'Gandhism',
    tagline: 'Non‑violent resistance, simple living, and local self‑reliance.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Based on the teachings of Mahatma Gandhi, this philosophy emphasises satyagraha (truth‑force), non‑violent civil disobedience, and economic self‑sufficiency through village industries.',
    relevance: 'Gandhi\'s early activism in SA shaped his philosophy, and his legacy influences peace movements and community development approaches in the country.',
    tradeoffs: '<strong>Pros:</strong> Provides a moral framework for social change without violence.<br><strong>Cons:</strong> Can be ineffective against regimes willing to use extreme force.',
    whyYouBelong: 'You believe in non‑violent resistance, community self‑reliance, and a moral approach to politics.',
    historical: 'Indian independence movement, US civil rights movement, anti‑apartheid struggle (partially).',
    saManifestation: 'Satyagraha campaigns, community development NGOs, some faith‑based movements.',
    metrics: { econIntervention: 4, individualAutonomy: 9, stability: 'HIGH' }
  },

  // ═══════════════════════════════════════════
  // LIBERTARIAN RIGHT (Yellow)
  // ═══════════════════════════════════════════
  'classical-liberalism': {
    title: 'Classical Liberalism',
    tagline: 'Individual freedom, limited government, and open markets.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Champions the protection of private property, free enterprise, rule of law, and strict constitutional limitations against government overreach.',
    relevance: 'The DA\'s core philosophy. Drives arguments for privatising SOEs, slashing red tape, and opposing BEE and NHI.',
    tradeoffs: '<strong>Pros:</strong> Optimises economic productivity, private sector investment, and personal liberties.<br><strong>Cons:</strong> Can expand wealth gaps if historical inequities are ignored.',
    whyYouBelong: 'You consistently favour market solutions, individual responsibility, and limited government. You believe freedom is the highest political good.',
    historical: 'Adam Smith, John Locke, 19th‑century British liberalism.',
    saManifestation: 'DA, FF+ (economic), UIM.',
    metrics: { econIntervention: 2, individualAutonomy: 9, stability: 'MODERATE-HIGH' }
  },
  'libertarianism': {
    title: 'Libertarianism',
    tagline: 'Maximum individual freedom, minimal state.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Advocates for a radically reduced state, limited to protecting individual rights, with free markets governing all economic and social activity.',
    relevance: 'The UIM and libertarian factions within the DA advocate for drastic reductions in government size and scope.',
    tradeoffs: '<strong>Pros:</strong> Maximises personal freedom and economic efficiency.<br><strong>Cons:</strong> Can lead to extreme inequality and the erosion of public goods.',
    whyYouBelong: 'You want the government out of both the economy and your personal life. You see taxation as theft and individual choice as paramount.',
    historical: 'Murray Rothbard, Ron Paul, US Libertarian Party.',
    saManifestation: 'UIM, some DA factions, libertarian think tanks.',
    metrics: { econIntervention: 1, individualAutonomy: 10, stability: 'LOW' }
  },
  'neo-liberalism': {
    title: 'Neo-Liberalism',
    tagline: 'Market efficiency balanced with smart institutional guardrails.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Maintains free‑market capitalism as its core but supports targeted regulatory protections and strategic social safety nets to keep conditions fair.',
    relevance: 'The DA\'s moderate wing, ActionSA, and BOSA all operate within a neo‑liberal framework, advocating for fiscal discipline with some social intervention.',
    tradeoffs: '<strong>Pros:</strong> Encourages investor confidence and balanced budgets.<br><strong>Cons:</strong> Can favour technocratic policies disconnected from grassroots realities.',
    whyYouBelong: 'You prefer market mechanisms but accept a role for the state in correcting market failures and providing a minimal safety net.',
    historical: 'Thatcherism, Reaganomics, Third Way politics.',
    saManifestation: 'DA moderate wing, ActionSA, BOSA.',
    metrics: { econIntervention: 3, individualAutonomy: 8, stability: 'HIGH' }
  },
  'fiscal-conservatism': {
    title: 'Fiscal Conservatism',
    tagline: 'Balanced budgets, low taxes, and limited government spending.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Prioritises fiscal responsibility, arguing that government should live within its means, avoid debt, and keep taxes low to encourage economic growth.',
    relevance: 'The DA and ActionSA emphasise fiscal discipline and reducing the national debt, criticising ANC government spending and SOE bailouts.',
    tradeoffs: '<strong>Pros:</strong> Prevents unsustainable debt and inflation.<br><strong>Cons:</strong> Can lead to austerity and underfunding of essential services.',
    whyYouBelong: 'You worry about government debt and believe that balanced budgets and low taxes are the foundation of a healthy economy.',
    historical: 'Traditional Republican economics, German ordoliberalism.',
    saManifestation: 'DA, ActionSA, FF+ (economic policy).',
    metrics: { econIntervention: 2, individualAutonomy: 7, stability: 'HIGH' }
  },
  'anarcho-capitalism': {
    title: 'Anarcho-Capitalism',
    tagline: 'A stateless society governed entirely by free markets.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Abolishes the state entirely, replacing all government functions — including law, defence, and infrastructure — with voluntary, market‑based alternatives.',
    relevance: 'Virtually no SA party advocates this, but elements of the UIM and radical libertarian groups flirt with its logic.',
    tradeoffs: '<strong>Pros:</strong> Absolute individual freedom.<br><strong>Cons:</strong> No empirical examples; would likely lead to private tyranny and the collapse of public goods.',
    whyYouBelong: 'You believe the state is inherently coercive and that all social problems can be solved through voluntary exchange and private enterprise.',
    historical: 'Murray Rothbard, David Friedman, theoretical only.',
    saManifestation: 'Fringe libertarian groups, not a mainstream platform.',
    metrics: { econIntervention: 0, individualAutonomy: 10, stability: 'LOW' }
  },
  'national-libertarianism': {
    title: 'National Libertarianism',
    tagline: 'Free markets and individual liberty within a sovereign nation.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Combines libertarian economics with nationalist cultural policies, supporting open markets internally but strict border controls and national sovereignty.',
    relevance: 'ActionSA and the PA combine pro‑business economics with anti‑immigration stances, aligning with this ideology.',
    tradeoffs: '<strong>Pros:</strong> Protects national identity while promoting economic freedom.<br><strong>Cons:</strong> Can justify xenophobia and undermine international cooperation.',
    whyYouBelong: 'You want economic freedom at home but believe the nation should control its borders and preserve its cultural identity.',
    historical: 'Some European right‑wing parties, US "America First" movement.',
    saManifestation: 'ActionSA, PA, some DA right‑wing factions.',
    metrics: { econIntervention: 2, individualAutonomy: 7, stability: 'MODERATE' }
  },
  'liberal-conservatism': {
    title: 'Liberal Conservatism',
    tagline: 'Free markets combined with traditional social values.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Advocates for economic liberalism and limited government, while upholding conservative positions on family, religion, and cultural issues.',
    relevance: 'The FF+ and ACDP represent this fusion in SA, combining free‑market economics with socially conservative platforms.',
    tradeoffs: '<strong>Pros:</strong> Provides a coherent fusion of economic and social conservatism.<br><strong>Cons:</strong> Social conservatism can conflict with individual rights.',
    whyYouBelong: 'You want the government out of the economy but believe it should uphold traditional moral values and cultural norms.',
    historical: 'Angela Merkel\'s CDU, David Cameron\'s Conservatives.',
    saManifestation: 'FF+, ACDP, some DA conservatives.',
    metrics: { econIntervention: 3, individualAutonomy: 5, stability: 'MODERATE-HIGH' }
  },
  'transhumanism': {
    title: 'Transhumanism',
    tagline: 'Using technology to transcend human biological limitations.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Advocates for the ethical use of technology to enhance human capabilities, extend lifespan, and ultimately overcome biological constraints.',
    relevance: 'Not a mainstream SA political platform, but tech‑focused policy discussions around AI, biotech, and digital rights touch on transhumanist themes.',
    tradeoffs: '<strong>Pros:</strong> Could revolutionise health, intelligence, and longevity.<br><strong>Cons:</strong> Raises profound ethical, equality, and existential risks.',
    whyYouBelong: 'You are a techno‑optimist who believes that human progress should be accelerated through science and technology, with minimal state interference.',
    historical: 'Silicon Valley futurism, extropian movement.',
    saManifestation: 'Tech policy debates, not a party platform.',
    metrics: { econIntervention: 1, individualAutonomy: 10, stability: 'UNCERTAIN' }
  },
  'objectivism': {
    title: 'Objectivism',
    tagline: 'Rational self‑interest as the only moral foundation for society.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Based on Ayn Rand\'s philosophy, it holds that laissez‑faire capitalism is the only moral system, and that altruism and state intervention are destructive.',
    relevance: 'The UIM and some libertarian activists in SA draw on Objectivist ideas, though no major party explicitly endorses Rand.',
    tradeoffs: '<strong>Pros:</strong> Provides a philosophical defence of capitalism and individualism.<br><strong>Cons:</strong> Dismisses altruism and collective responsibility, and has been widely criticised by philosophers.',
    whyYouBelong: 'You believe that pursuing your own rational self‑interest is the highest moral good, and that the state should not interfere with individual achievement.',
    historical: 'Ayn Rand\'s novels and essays, influence on some US libertarians.',
    saManifestation: 'UIM, some libertarian think tanks.',
    metrics: { econIntervention: 1, individualAutonomy: 10, stability: 'LOW' }
  },
  'minarchism': {
    title: 'Minarchism',
    tagline: 'The "night‑watchman state" — government limited to protecting rights.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Advocates for a state that exists only to enforce contracts, protect private property, and provide national defence, with all other functions left to the market.',
    relevance: 'The UIM and the DA\'s most libertarian factions advocate for drastically reducing the state to core functions.',
    tradeoffs: '<strong>Pros:</strong> Dramatically reduces government coercion and waste.<br><strong>Cons:</strong> Would dismantle the welfare state and public services.',
    whyYouBelong: 'You want a government so small it is almost invisible, limited to police, courts, and the military.',
    historical: 'Robert Nozick, classical liberal tradition.',
    saManifestation: 'UIM, DA right‑wing.',
    metrics: { econIntervention: 1, individualAutonomy: 9, stability: 'MODERATE' }
  },
  'paleo-libertarianism': {
    title: 'Paleo-Libertarianism',
    tagline: 'Radical libertarianism with traditional cultural values.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Combines extreme economic libertarianism with paleo‑conservative cultural positions, opposing both state intervention and progressive social movements.',
    relevance: 'Some factions within the FF+ and UIM combine libertarian economics with culturally conservative positions, particularly on issues like language and education.',
    tradeoffs: '<strong>Pros:</strong> Consistent in opposing state power in both economic and cultural spheres.<br><strong>Cons:</strong> Cultural conservatism can conflict with individual liberty for all.',
    whyYouBelong: 'You want radical economic freedom but also believe in preserving traditional cultural norms, even if that requires social conformity.',
    historical: 'Ron Paul movement, some strands of US libertarianism.',
    saManifestation: 'FF+, UIM, some conservative Afrikaner intellectuals.',
    metrics: { econIntervention: 1, individualAutonomy: 6, stability: 'MODERATE' }
  },

  // ═══════════════════════════════════════════
  // SA‑SPECIFIC / HYBRID
  // ═══════════════════════════════════════════
  'pan-africanism': {
    title: 'Pan-Africanism',
    tagline: 'African unity, solidarity, and liberation from neo‑colonialism.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'A worldwide movement that aims to encourage and strengthen bonds of solidarity between all indigenous and diaspora peoples of African ancestry. Advocates for continental unity, economic self‑determination, and cultural pride.',
    relevance: 'The EFF, PAC, and some ANC factions explicitly advocate Pan‑Africanist foreign policy, including withdrawal from the ICC, strengthening the AU, and opposing Western intervention.',
    tradeoffs: '<strong>Pros:</strong> Fosters continental solidarity and challenges Western hegemony.<br><strong>Cons:</strong> Can be used to defend authoritarian regimes under the banner of African solidarity.',
    whyYouBelong: 'You believe Africa\'s problems require African solutions, and you support continental integration, anti‑imperialism, and solidarity with oppressed people globally.',
    historical: 'Kwame Nkrumah, Julius Nyerere, Patrice Lumumba, Robert Sobukwe.',
    saManifestation: 'EFF, PAC, ANC (foreign policy), AZAPO.',
    metrics: { econIntervention: 6, individualAutonomy: 6, stability: 'MODERATE' }
  },
  'african-nationalism': {
    title: 'African Nationalism',
    tagline: 'Political self‑determination for African peoples.',
    quadrant: 'AUTHORITARIAN LEFT',
    summary: 'The ideology that drove the liberation struggle, emphasising the right of African people to govern themselves, reclaim their land, and build a state that reflects African values.',
    relevance: 'The ANC was founded on African nationalism, and it remains a powerful undercurrent, particularly in debates around land reform, BEE, and cultural policy.',
    tradeoffs: '<strong>Pros:</strong> Provided the moral and political energy for decolonisation.<br><strong>Cons:</strong> Can marginalise non‑African minorities and conflict with non‑racial constitutionalism.',
    whyYouBelong: 'You believe that African people should be at the centre of SA\'s political and economic life, redressing the legacy of colonialism and apartheid.',
    historical: 'ANC, PAC, African independence movements.',
    saManifestation: 'ANC, PAC, EFF, ATM.',
    metrics: { econIntervention: 6, individualAutonomy: 4, stability: 'MODERATE' }
  },
  'non-racialism': {
    title: 'Non-Racialism',
    tagline: 'A society where race is irrelevant to life outcomes.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'The principle that race should not determine access to resources, rights, or opportunities. Enshrined in the SA Constitution, it is a rejection of both apartheid and racial nationalism.',
    relevance: 'The DA, BOSA, and RISE Mzansi explicitly champion non‑racialism, though critics argue it can ignore the ongoing material reality of racial inequality.',
    tradeoffs: '<strong>Pros:</strong> Provides a vision of a truly equal, integrated society.<br><strong>Cons:</strong> Can be used to oppose race‑based transformation policies like BEE.',
    whyYouBelong: 'You believe that race should not matter in a just society, and you support policies that move SA beyond racial categories.',
    historical: 'Freedom Charter, Black Consciousness (in its non‑racial form), Constitution of SA.',
    saManifestation: 'DA, BOSA, RISE Mzansi, ANC non‑racial tradition.',
    metrics: { econIntervention: 4, individualAutonomy: 8, stability: 'HIGH' }
  },
  'ubuntu-communitarianism': {
    title: 'Ubuntu Communitarianism',
    tagline: '"I am because we are" — collective dignity and mutual responsibility.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Rooted in African philosophy, ubuntu emphasises interconnectedness, compassion, and the idea that individual humanity is realised through community. It underpins the constitutional value of human dignity.',
    relevance: 'The TRC, social grant system, and many SA policy debates invoke ubuntu as a guiding principle, though its practical application is contested.',
    tradeoffs: '<strong>Pros:</strong> Provides a unique African ethical framework for social justice.<br><strong>Cons:</strong> Can be vague and difficult to translate into specific policies.',
    whyYouBelong: 'You believe that community and mutual care should be at the heart of politics, and that individual success is meaningless without collective well‑being.',
    historical: 'Pre‑colonial African societies, Tutu\'s theology, Constitution of SA.',
    saManifestation: 'TRC, social welfare policies, ANC rhetoric, civil society.',
    metrics: { econIntervention: 5, individualAutonomy: 6, stability: 'MODERATE-HIGH' }
  },
  'decolonialism': {
    title: 'Decolonialism',
    tagline: 'Dismantling colonial structures in knowledge, culture, and power.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Goes beyond political independence to challenge the enduring coloniality of power, knowledge, and being. Advocates for the decolonisation of education, language, and institutions.',
    relevance: '#RhodesMustFall and #FeesMustFall brought decolonial ideas to the forefront of SA public discourse, challenging Eurocentric curricula and institutional cultures.',
    tradeoffs: '<strong>Pros:</strong> Forces a reckoning with the deep structures of coloniality.<br><strong>Cons:</strong> Can be polarising and sometimes struggles to articulate a clear policy agenda.',
    whyYouBelong: 'You believe that political freedom is incomplete without cultural and intellectual liberation from colonial paradigms.',
    historical: 'Frantz Fanon, Steve Biko, Latin American decolonial thinkers.',
    saManifestation: 'Student movements, some PAC and AZAPO rhetoric, academic discourse.',
    metrics: { econIntervention: 5, individualAutonomy: 8, stability: 'MODERATE' }
  },
  'third-way': {
    title: 'Third Way',
    tagline: 'Beyond left and right — pragmatic, evidence‑based centrism.',
    quadrant: 'LIBERTARIAN LEFT',
    summary: 'Seeks to reconcile market economics with social justice, rejecting both rigid socialism and laissez‑faire capitalism. Emphasises technocratic governance and what works.',
    relevance: 'RISE Mzansi and BOSA explicitly position themselves as post‑ideological, evidence‑based alternatives to traditional left‑right politics.',
    tradeoffs: '<strong>Pros:</strong> Flexible, pragmatic, and avoids ideological dogma.<br><strong>Cons:</strong> Can lack a clear moral compass and fail to inspire strong loyalty.',
    whyYouBelong: 'You are tired of ideological battles and want practical solutions that work, drawing on both market mechanisms and state intervention as needed.',
    historical: 'Bill Clinton\'s New Democrats, Tony Blair\'s New Labour, Macron\'s En Marche.',
    saManifestation: 'RISE Mzansi, BOSA, GOOD (partially).',
    metrics: { econIntervention: 4, individualAutonomy: 7, stability: 'HIGH' }
  },
  'christian-democracy': {
    title: 'Christian Democracy',
    tagline: 'Christian ethics as the foundation of a market economy with a social conscience.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Emphasises the compatibility of Christian values with democratic governance and a social market economy. Supports family values, subsidiarity, and the common good.',
    relevance: 'The ACDP is SA\'s primary Christian democratic party, advocating for biblical principles in public policy.',
    tradeoffs: '<strong>Pros:</strong> Provides a moral framework for capitalism and social welfare.<br><strong>Cons:</strong> Can conflict with secularism and the rights of non‑Christian minorities.',
    whyYouBelong: 'You believe that Christian ethics should guide economic and social policy, balancing market freedom with compassion for the poor.',
    historical: 'German CDU, Italian Christian Democrats, European People\'s Party.',
    saManifestation: 'ACDP, some faith‑based civil society organisations.',
    metrics: { econIntervention: 4, individualAutonomy: 5, stability: 'HIGH' }
  },
  'eco-conservatism': {
    title: 'Eco-Conservatism',
    tagline: 'Conserving nature as part of conserving tradition and heritage.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Combines environmental protection with conservative values, arguing that stewardship of the land is a traditional responsibility and that market mechanisms can achieve conservation goals.',
    relevance: 'Game farming, rhino conservation, and responsible tourism are areas where SA eco‑conservatism finds expression, often linked to property rights and market‑based conservation.',
    tradeoffs: '<strong>Pros:</strong> Can mobilise conservative communities for environmental causes.<br><strong>Cons:</strong> May prioritise property rights over environmental justice.',
    whyYouBelong: 'You believe in protecting the natural environment as part of preserving national heritage, and you prefer market‑based solutions to environmental problems.',
    historical: 'Theodore Roosevelt\'s conservationism, UK Conservative environmental tradition.',
    saManifestation: 'Game farming lobby, some FF+ and DA environmental policies.',
    metrics: { econIntervention: 3, individualAutonomy: 6, stability: 'MODERATE' }
  },
  'national-liberalism': {
    title: 'National Liberalism',
    tagline: 'Free markets and individual liberty within a strong nation‑state.',
    quadrant: 'LIBERTARIAN RIGHT',
    summary: 'Combines classical liberal economics with nationalist cultural policies, supporting open markets internally but asserting national sovereignty and identity.',
    relevance: 'ActionSA and the PA embody this blend in SA, combining pro‑business policies with strong anti‑immigration and national identity rhetoric.',
    tradeoffs: '<strong>Pros:</strong> Appeals to both economic and cultural concerns.<br><strong>Cons:</strong> Can legitimise xenophobia and undermine international cooperation.',
    whyYouBelong: 'You want economic freedom at home but believe the nation should control its borders and preserve its cultural identity against globalising forces.',
    historical: '19th‑century European liberalism, modern right‑wing populism.',
    saManifestation: 'ActionSA, PA, some DA right‑wing factions.',
    metrics: { econIntervention: 2, individualAutonomy: 7, stability: 'MODERATE' }
  }
};